### ISSUE TITLE
about data

### ISSUE THREAD

**Issue by helloxuelian** [hyyc116/CitLab#1]
Hello, I'm very sorry to disturb you. I'm also doing some work about citation network. As it's just started, I'm studying. I see that your project is well done. Can I ask if this dataset can be provided?

**Comment by hyyc116** [comment]
The dataset I used is the APS dataset,which contains citation relations and some meta data, is a popular dataset for bibliometrics. it is a open data but need an application. I am sorry for I cannot share you directly according to their regulations. The link for application is https://journals.aps.org/datasets . After getting access, they will send you a link for downloading.

**Comment by helloxuelian** [comment]
Ok, thank you very much！
