### ISSUE TITLE
希望能够获得您的联系方式

### ISSUE THREAD

**Issue by helloxuelian** [hyyc116/CitLab#2]
您好，我在看了您的GitHub相关代码后，觉得您在引文网络方面有相当丰富的研究并且写代码能力很强。我的研究课题目前也是文献分析的，我最近也在看相关论文和相关研究，但是处于入门阶段，非常希望能够加您的qq或者微信了解一些更详细的内容，不知道您是否方便？我的qq是825318223，微信是13671386329。如有打扰，非常抱歉！

**Comment by hyyc116** [comment]
微信号 hyyc116&nbsp;



发自我的iPhone


------------------ 原始邮件 ------------------
发件人: helloxuelian <notifications@github.com&gt;
发送时间: 2020年6月11日 10:47
收件人: hyyc116/CitLab <CitLab@noreply.github.com&gt;
抄送: Subscribed <subscribed@noreply.github.com&gt;
主题: 回复：[hyyc116/CitLab] 希望能够获得您的联系方式 (#2)
